%FSM plotter
figure
subplot(5,1,1)
plot(pos(:,1), pos(:,2), 'LineWidth', 2)
axis([-inf max(state(:,1)) -inf inf])
title('Current Knob Position (w/ reference lines)')
xlabel('Time (s)')
ylabel('Position (deg)')
refline(0, 80)
refline(0, 100)
subplot(5,1,2)
plot(vel(:,1), vel(:,2), 'LineWidth', 2)
axis([-inf max(state(:,1)) -inf inf])
title('Current Knob Velocity')
xlabel('Time (s)')
ylabel('Velocity (rpm)')
subplot(5,1,3)
plot(current(:,1), current(:,2), 'LineWidth', 2)
axis([-inf max(state(:,1)) -inf inf])
title('Current to motor')
xlabel('Time (s)')
ylabel('Current (A)')
subplot(5,1,4)
plot(pert(:,1), pert(:,2), 'LineWidth', 2)
axis([-inf max(state(:,1)) -inf inf])
title('Perturbation enable')
xlabel('Time (s)')
ylabel('Perturbation')
subplot(5,1,5)
plot(state(:,1), state(:,2), 'LineWidth', 2)
title('FSM Current State')
xlabel('Time (s)')
ylabel('State')
axis([0 max(state(:,1)) 0 4])